import 'bootstrap/dist/css/bootstrap.min.css';
import ReduxWrapper from '../../redux/ReduxWrapper';
export const metadata = {
  title: 'Meal Management',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ReduxWrapper>
      <html lang="en">
        <body>{children}</body>
      </html>
    </ReduxWrapper>
  );
}
